//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPnetPhishing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInvoice
    {
        public System.DateTime Invoice_Date { get; set; }
        public decimal Invoice_Total { get; set; }
        public string Customer_Email { get; set; }
        public string Card_Number { get; set; }
        public string Ship_To { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    }
}
